import type { Metadata } from 'next'
import Link from 'next/link'
import { Email, LegalPage } from '../legal'

export const metadata: Metadata = { title: 'Terms of use | CarMart' }

export default function TermsPage() {
  return (
    <LegalPage title="Terms of use">
      <p>These terms apply when you use CarMart to look for, list or ask about cars. By using CarMart you agree to them.</p>

      <h2>What CarMart is</h2>
      <p>CarMart is a listing platform. Verified car dealers and sellers (“shops”) list cars, and buyers contact them. <strong>CarMart is not a party to any sale.</strong> We don’t own, inspect, sell or deliver the cars, and we don’t take payments or deposits. The price, inspection, payment, paperwork and handover are agreed between the buyer and the seller.</p>

      <h2>Accounts and shops</h2>
      <ul>
        <li>You must give accurate information and keep your password safe.</li>
        <li>Sellers must verify a Nigerian mobile number, and every shop is approved by our team before it can list cars.</li>
        <li>We may refuse, suspend or close accounts and shops that break these terms or our <Link href="/prohibited-listings">Prohibited listings</Link> rules.</li>
      </ul>

      <h2>Listings</h2>
      <ul>
        <li>Sellers must own the car or have the right to sell it, and describe it honestly: price, kilometres, condition, VIN and location.</li>
        <li>Only cars may be listed, with real photos of the actual car.</li>
        <li>Listings stay live for 60 days and can be renewed. We may remove any listing that breaks these terms.</li>
      </ul>

      <h2>How photo checks work</h2>
      <p>Every photo is checked automatically before a listing goes live: we check that it shows a car and look for signs that it was generated by AI or copied from elsewhere. Suspicious photos are rejected or reviewed by our team. These checks reduce the risk of fake listings, but <strong>they are not a guarantee</strong> that a listing, a car or a seller is genuine. Always inspect the car and its papers yourself (see <Link href="/buyer-safety">Buyer safety</Link>).</p>

      <h2>Your responsibilities</h2>
      <ul>
        <li>Don’t post false, misleading or unlawful content, or use CarMart to harass, defraud or spam anyone.</li>
        <li>Don’t try to get around our checks, limits or security.</li>
      </ul>

      <h2>Liability</h2>
      <p>CarMart is provided as it is. To the extent the law allows, we aren’t responsible for the condition, legality or ownership of any car, for what buyers and sellers agree, or for losses from dealings between them. Nothing in these terms limits rights you have under the Federal Competition and Consumer Protection Act 2018 or other Nigerian law that can’t be limited.</p>

      <h2>Law</h2>
      <p>These terms are governed by the laws of the Federal Republic of Nigeria.</p>

      <h2>Contact</h2>
      <p>Questions about these terms: <Email />.</p>
    </LegalPage>
  )
}
