#!/usr/bin/env bash
# worktree-run.sh — run all issues in a phase as parallel worktrees
# GENERATED by /plan-issues — do not edit phase arrays manually
# Usage: ./scripts/worktree-run.sh [phase-number]

# NOTE: No set -e — errors handled explicitly so subshells do not die silently

PHASE="${1}"
WORKTREE_BASE="$(pwd)/.worktrees"
APP_ROOT="$(pwd)"

if [ -z "$PHASE" ]; then
  echo "Usage: ./scripts/worktree-run.sh [phase-number]"
  exit 1
fi

PHASE_1_ISSUES=("001-dev-test-infrastructure")
PHASE_2_ISSUES=("002-foundation-schema" "017-image-decision-table-and-fakes")
PHASE_3_ISSUES=("003-supabase-clients-and-sign-up" "006-job-runner-and-email-dispatch" "019-real-image-check-providers")
PHASE_4_ISSUES=("004-sign-in-reset-header")
PHASE_5_ISSUES=("005-profile-api-and-suspension")
PHASE_6_ISSUES=("007-create-shop" "013-vehicle-reference-data")
PHASE_7_ISSUES=("008-edit-shop-and-public-page" "014-listings-table-and-draft-api")
PHASE_8_ISSUES=("009-phone-verification" "015-listing-draft-form" "016-photo-upload-api")
PHASE_9_ISSUES=("010-submit-shop-for-approval" "018-image-verification-pipeline" "020-photo-uploader-ui")
PHASE_10_ISSUES=("011-admin-area-and-shop-queue")
PHASE_11_ISSUES=("012-admin-approve-reject-shop")
PHASE_12_ISSUES=("021-submit-listing-and-go-live")
PHASE_13_ISSUES=("022-listing-view-api-and-emails" "039-admin-image-review-queue")
PHASE_14_ISSUES=("023-edit-live-listing" "026-search-service-and-api" "033-conversations-schema-and-service")
PHASE_15_ISSUES=("024-mark-sold-and-unpublish" "027-cars-search-page-and-home")
PHASE_16_ISSUES=("025-expiry-reminders-and-renew" "028-listing-detail-page")
PHASE_17_ISSUES=("029-saved-cars" "040-admin-approve-reject-photo")
PHASE_18_ISSUES=("030-seo-metadata-footer" "041-admin-listing-review-queues")
PHASE_19_ISSUES=("031-legal-and-trust-pages" "034-message-seller-ui-and-buyer-inbox" "042-admin-listing-actions")
PHASE_20_ISSUES=("032-e2e-journeys-and-accessibility" "035-seller-inbox")
PHASE_21_ISSUES=("036-message-email-alerts")
PHASE_22_ISSUES=("037-show-seller-phone")
PHASE_23_ISSUES=("038-block-conversation")
PHASE_24_ISSUES=("043-reports-and-auto-hide")
PHASE_25_ISSUES=("044-reports-queue-and-conversation-reports")
PHASE_26_ISSUES=("045-suspensions-and-listing-caps")
PHASE_27_ISSUES=("046-admin-settings")
PHASE_28_ISSUES=("047-audit-log")

PHASE_VAR="PHASE_${PHASE}_ISSUES[@]"
ISSUES=("${!PHASE_VAR}")

if [ ${#ISSUES[@]} -eq 0 ]; then
  echo "No issues for Phase $PHASE."
  exit 1
fi

echo "Parallel worktrees: ${#ISSUES[@]}"
git checkout main && git pull
mkdir -p "$WORKTREE_BASE"

PIDS=()
SLUGS=()

for ISSUE_SLUG in "${ISSUES[@]}"; do
  NNN="${ISSUE_SLUG%%-*}"
  BRANCH="feature/${ISSUE_SLUG}"
  WORKTREE_PATH="${WORKTREE_BASE}/${ISSUE_SLUG}"

  [ -d "$WORKTREE_PATH" ] && {
    git worktree remove "$WORKTREE_PATH" --force 2>/dev/null || true
    git branch -D "$BRANCH" 2>/dev/null || true
  }

  git worktree add "$WORKTREE_PATH" -b "$BRANCH" main

  ISSUE_FILE=$(ls "$APP_ROOT"/issues/open/${NNN}-*.md | head -1)
  ISSUE_CONTENT=$(cat "$ISSUE_FILE")
  EPICS=$(cat "$APP_ROOT"/issues/epics/*.md 2>/dev/null || echo "")
  FEATURES=$(find "$APP_ROOT/issues/features" -name "*.md" | xargs cat 2>/dev/null || echo "")
  IMPLEMENT_PROMPT=$(awk '/^---/{i++} i>=2{print} i<2 && /^---/{next}' \
    "$APP_ROOT/.claude/skills/implement/SKILL.md" 2>/dev/null || echo "skill not found")
  AUDIT_PROMPT=$(awk '/^---/{i++} i>=2{print} i<2 && /^---/{next}' \
    "$APP_ROOT/.claude/skills/audit/SKILL.md" 2>/dev/null || echo "skill not found")
  SPEC_DOCS=$(cat "$APP_ROOT"/docs/*.md 2>/dev/null || echo "no spec docs")
  LOG_FILE="${WORKTREE_BASE}/${ISSUE_SLUG}.log"
  AUDIT_LOG="${WORKTREE_BASE}/${ISSUE_SLUG}.audit.log"

  (
    cd "$WORKTREE_PATH"
    FULL_PROMPT="$IMPLEMENT_PROMPT

---
EPICS:
$EPICS

---
FEATURES:
$FEATURES

---
ISSUES:
$ISSUE_CONTENT"

    OUTPUT=$(echo "$FULL_PROMPT" | claude --permission-mode acceptEdits -p 2>&1)
    echo "$OUTPUT" > "$LOG_FILE"

    echo "$OUTPUT" | grep -q "\[BLOCKED" && exit 2

    DIFF=$(git diff main...HEAD)
    [ -z "$DIFF" ] && exit 3

    AUDIT_FULL_PROMPT="$AUDIT_PROMPT

---
ISSUE:
$ISSUE_CONTENT

---
SPEC_DOCS:
$SPEC_DOCS

---
DIFF:
$DIFF"

    AUDIT=$(echo "$AUDIT_FULL_PROMPT" | claude -p)
    echo "$AUDIT" > "$AUDIT_LOG"

    echo "$AUDIT" | grep -q "\[APPROVED\]" || exit 1

    git push -u origin "$BRANCH"
    exit 0
  ) &
  PIDS+=($!)
  SLUGS+=("$ISSUE_SLUG")
done

APPROVED=(); FAILED=(); BLOCKED=(); ERROR=()
for i in "${!PIDS[@]}"; do
  wait "${PIDS[$i]}"; CODE=$?
  case $CODE in
    0) APPROVED+=("${SLUGS[$i]}") ;;
    1) FAILED+=("${SLUGS[$i]}") ;;
    2) BLOCKED+=("${SLUGS[$i]}") ;;
    *) ERROR+=("${SLUGS[$i]}") ;;
  esac
done

echo "✓ APPROVED + pushed: ${#APPROVED[@]} — open PRs on GitHub"
[ ${#FAILED[@]} -gt 0 ] && echo "✗ AUDIT FAILED: ${#FAILED[@]}"
[ ${#BLOCKED[@]} -gt 0 ] && echo "⚠ BLOCKED: ${#BLOCKED[@]}"
echo ""
echo "Next: open PRs → review → merge → ./scripts/worktree-merge.sh $PHASE"
