-- Issue 013: car-only make/model reference data (docs/schema.md → vehicle_makes, vehicle_models).
-- Reference data lives in a migration (not seed.sql) so production has it too.
-- Source of truth: scripts/data/vehicle-reference.json (regenerate this migration's data block from it).

create table public.vehicle_makes (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(name) between 1 and 40),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.vehicle_models (
  id uuid primary key default gen_random_uuid(),
  make_id uuid not null references public.vehicle_makes(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 40),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_models_make_name_key unique (make_id, name)
);
create index vehicle_models_make_idx on public.vehicle_models (make_id, name) where active;
create trigger vehicle_makes_set_updated_at before update on public.vehicle_makes for each row execute function public.set_updated_at();
create trigger vehicle_models_set_updated_at before update on public.vehicle_models for each row execute function public.set_updated_at();

alter table public.vehicle_makes enable row level security;
alter table public.vehicle_models enable row level security;
revoke all on public.vehicle_makes, public.vehicle_models from anon, authenticated;
grant select on public.vehicle_makes, public.vehicle_models to anon, authenticated;
grant insert, update, delete on public.vehicle_makes, public.vehicle_models to authenticated;
create policy vehicle_makes_read on public.vehicle_makes for select to anon, authenticated using (true);
create policy vehicle_models_read on public.vehicle_models for select to anon, authenticated using (true);
create policy vehicle_makes_admin_write on public.vehicle_makes for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy vehicle_models_admin_write on public.vehicle_models for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.vehicle_makes (name) values
  ('Abarth'),
  ('Alfa Romeo'),
  ('Aston Martin'),
  ('Audi'),
  ('BMW'),
  ('BYD'),
  ('Bentley'),
  ('Chery'),
  ('Chevrolet'),
  ('Chrysler'),
  ('Citroen'),
  ('Cupra'),
  ('Dodge'),
  ('Ferrari'),
  ('Fiat'),
  ('Ford'),
  ('GWM'),
  ('Genesis'),
  ('Haval'),
  ('Holden'),
  ('Honda'),
  ('Hyundai'),
  ('Isuzu'),
  ('Jaguar'),
  ('Jeep'),
  ('Kia'),
  ('LDV'),
  ('Lamborghini'),
  ('Land Rover'),
  ('Lexus'),
  ('Lotus'),
  ('MG'),
  ('Maserati'),
  ('Mazda'),
  ('McLaren'),
  ('Mercedes-Benz'),
  ('Mini'),
  ('Mitsubishi'),
  ('Nissan'),
  ('Peugeot'),
  ('Polestar'),
  ('Porsche'),
  ('Ram'),
  ('Renault'),
  ('Rolls-Royce'),
  ('Skoda'),
  ('Smart'),
  ('SsangYong'),
  ('Subaru'),
  ('Suzuki'),
  ('Tesla'),
  ('Toyota'),
  ('Volkswagen'),
  ('Volvo'),
  ('Zeekr')
on conflict (name) do nothing;

insert into public.vehicle_models (make_id, name)
select mk.id, v.model from (values
  ('Abarth', '595'),
  ('Abarth', '695'),
  ('Abarth', '124 Spider'),
  ('Abarth', '500e'),
  ('Alfa Romeo', 'Giulia'),
  ('Alfa Romeo', 'Stelvio'),
  ('Alfa Romeo', 'Tonale'),
  ('Alfa Romeo', 'Giulietta'),
  ('Alfa Romeo', '4C'),
  ('Alfa Romeo', '159'),
  ('Alfa Romeo', 'Brera'),
  ('Alfa Romeo', 'MiTo'),
  ('Aston Martin', 'DB11'),
  ('Aston Martin', 'DB12'),
  ('Aston Martin', 'DBX'),
  ('Aston Martin', 'Vantage'),
  ('Aston Martin', 'DBS'),
  ('Aston Martin', 'Rapide'),
  ('Audi', 'A1'),
  ('Audi', 'A3'),
  ('Audi', 'A4'),
  ('Audi', 'A5'),
  ('Audi', 'A6'),
  ('Audi', 'A7'),
  ('Audi', 'A8'),
  ('Audi', 'Q2'),
  ('Audi', 'Q3'),
  ('Audi', 'Q4 e-tron'),
  ('Audi', 'Q5'),
  ('Audi', 'Q7'),
  ('Audi', 'Q8'),
  ('Audi', 'e-tron GT'),
  ('Audi', 'R8'),
  ('Audi', 'RS3'),
  ('Audi', 'RS4'),
  ('Audi', 'RS6'),
  ('Audi', 'S3'),
  ('Audi', 'TT'),
  ('BMW', '1 Series'),
  ('BMW', '2 Series'),
  ('BMW', '3 Series'),
  ('BMW', '4 Series'),
  ('BMW', '5 Series'),
  ('BMW', '7 Series'),
  ('BMW', '8 Series'),
  ('BMW', 'i3'),
  ('BMW', 'i4'),
  ('BMW', 'i5'),
  ('BMW', 'i7'),
  ('BMW', 'iX'),
  ('BMW', 'iX1'),
  ('BMW', 'iX3'),
  ('BMW', 'M2'),
  ('BMW', 'M3'),
  ('BMW', 'M4'),
  ('BMW', 'M5'),
  ('BMW', 'X1'),
  ('BMW', 'X2'),
  ('BMW', 'X3'),
  ('BMW', 'X4'),
  ('BMW', 'X5'),
  ('BMW', 'X6'),
  ('BMW', 'X7'),
  ('BMW', 'Z4'),
  ('BYD', 'Atto 3'),
  ('BYD', 'Dolphin'),
  ('BYD', 'Seal'),
  ('BYD', 'Sealion 6'),
  ('BYD', 'Sealion 7'),
  ('BYD', 'Shark 6'),
  ('Bentley', 'Bentayga'),
  ('Bentley', 'Continental GT'),
  ('Bentley', 'Flying Spur'),
  ('Bentley', 'Mulsanne'),
  ('Chery', 'Omoda 5'),
  ('Chery', 'Tiggo 4 Pro'),
  ('Chery', 'Tiggo 7 Pro'),
  ('Chery', 'Tiggo 8 Pro Max'),
  ('Chery', 'J11'),
  ('Chevrolet', 'Silverado'),
  ('Chevrolet', 'Corvette'),
  ('Chevrolet', 'Camaro'),
  ('Chrysler', '300'),
  ('Chrysler', '300C'),
  ('Chrysler', 'Grand Voyager'),
  ('Chrysler', 'Crossfire'),
  ('Citroen', 'C3'),
  ('Citroen', 'C4'),
  ('Citroen', 'C5 Aircross'),
  ('Citroen', 'C5 X'),
  ('Citroen', 'Berlingo Multispace'),
  ('Citroen', 'DS3'),
  ('Cupra', 'Born'),
  ('Cupra', 'Formentor'),
  ('Cupra', 'Leon'),
  ('Cupra', 'Ateca'),
  ('Cupra', 'Tavascan'),
  ('Dodge', 'Journey'),
  ('Dodge', 'Nitro'),
  ('Dodge', 'Caliber'),
  ('Dodge', 'Challenger'),
  ('Ferrari', '296 GTB'),
  ('Ferrari', '812 Superfast'),
  ('Ferrari', 'F8 Tributo'),
  ('Ferrari', 'Portofino'),
  ('Ferrari', 'Roma'),
  ('Ferrari', 'SF90 Stradale'),
  ('Ferrari', 'Purosangue'),
  ('Ferrari', '458 Italia'),
  ('Ferrari', '488 GTB'),
  ('Ferrari', 'California'),
  ('Fiat', '500'),
  ('Fiat', '500X'),
  ('Fiat', 'Panda'),
  ('Fiat', 'Punto'),
  ('Fiat', 'Tipo'),
  ('Fiat', 'Freemont'),
  ('Ford', 'Ranger'),
  ('Ford', 'Everest'),
  ('Ford', 'Mustang'),
  ('Ford', 'Mustang Mach-E'),
  ('Ford', 'Puma'),
  ('Ford', 'Escape'),
  ('Ford', 'Focus'),
  ('Ford', 'Fiesta'),
  ('Ford', 'Territory'),
  ('Ford', 'Falcon'),
  ('Ford', 'Falcon Ute'),
  ('Ford', 'Kuga'),
  ('Ford', 'Endura'),
  ('Ford', 'Mondeo'),
  ('Ford', 'Bronco'),
  ('Ford', 'F-150'),
  ('Ford', 'Tourneo'),
  ('GWM', 'Cannon'),
  ('GWM', 'Cannon Alpha'),
  ('GWM', 'Ora'),
  ('GWM', 'Steed'),
  ('GWM', 'Tank 300'),
  ('GWM', 'Tank 500'),
  ('Genesis', 'G70'),
  ('Genesis', 'G80'),
  ('Genesis', 'G90'),
  ('Genesis', 'GV60'),
  ('Genesis', 'GV70'),
  ('Genesis', 'GV80'),
  ('Haval', 'Jolion'),
  ('Haval', 'H6'),
  ('Haval', 'H6GT'),
  ('Haval', 'H2'),
  ('Haval', 'H9'),
  ('Holden', 'Commodore'),
  ('Holden', 'Commodore Ute'),
  ('Holden', 'Colorado'),
  ('Holden', 'Trailblazer'),
  ('Holden', 'Captiva'),
  ('Holden', 'Cruze'),
  ('Holden', 'Barina'),
  ('Holden', 'Astra'),
  ('Holden', 'Acadia'),
  ('Holden', 'Equinox'),
  ('Holden', 'Trax'),
  ('Holden', 'Spark'),
  ('Holden', 'Calais'),
  ('Holden', 'Caprice'),
  ('Holden', 'Statesman'),
  ('Holden', 'Monaro'),
  ('Holden', 'Rodeo'),
  ('Holden', 'Malibu'),
  ('Holden', 'Viva'),
  ('Honda', 'Accord'),
  ('Honda', 'City'),
  ('Honda', 'Civic'),
  ('Honda', 'CR-V'),
  ('Honda', 'HR-V'),
  ('Honda', 'Jazz'),
  ('Honda', 'Odyssey'),
  ('Honda', 'ZR-V'),
  ('Honda', 'Integra'),
  ('Honda', 'Legend'),
  ('Honda', 'Prelude'),
  ('Honda', 'S2000'),
  ('Honda', 'NSX'),
  ('Hyundai', 'Accent'),
  ('Hyundai', 'Elantra'),
  ('Hyundai', 'i20'),
  ('Hyundai', 'i30'),
  ('Hyundai', 'i30 N'),
  ('Hyundai', 'Ioniq'),
  ('Hyundai', 'Ioniq 5'),
  ('Hyundai', 'Ioniq 6'),
  ('Hyundai', 'Kona'),
  ('Hyundai', 'Palisade'),
  ('Hyundai', 'Santa Fe'),
  ('Hyundai', 'Sonata'),
  ('Hyundai', 'Staria'),
  ('Hyundai', 'Tucson'),
  ('Hyundai', 'Venue'),
  ('Hyundai', 'Veloster'),
  ('Hyundai', 'iLoad'),
  ('Hyundai', 'iMax'),
  ('Hyundai', 'Getz'),
  ('Hyundai', 'Genesis'),
  ('Isuzu', 'D-Max'),
  ('Isuzu', 'MU-X'),
  ('Isuzu', 'MU-7'),
  ('Jaguar', 'E-Pace'),
  ('Jaguar', 'F-Pace'),
  ('Jaguar', 'F-Type'),
  ('Jaguar', 'I-Pace'),
  ('Jaguar', 'XE'),
  ('Jaguar', 'XF'),
  ('Jaguar', 'XJ'),
  ('Jaguar', 'XK'),
  ('Jaguar', 'S-Type'),
  ('Jaguar', 'X-Type'),
  ('Jeep', 'Cherokee'),
  ('Jeep', 'Compass'),
  ('Jeep', 'Gladiator'),
  ('Jeep', 'Grand Cherokee'),
  ('Jeep', 'Renegade'),
  ('Jeep', 'Wrangler'),
  ('Jeep', 'Commander'),
  ('Jeep', 'Patriot'),
  ('Kia', 'Carnival'),
  ('Kia', 'Cerato'),
  ('Kia', 'EV5'),
  ('Kia', 'EV6'),
  ('Kia', 'EV9'),
  ('Kia', 'Niro'),
  ('Kia', 'Picanto'),
  ('Kia', 'Rio'),
  ('Kia', 'Seltos'),
  ('Kia', 'Sorento'),
  ('Kia', 'Soul'),
  ('Kia', 'Sportage'),
  ('Kia', 'Stinger'),
  ('Kia', 'Stonic'),
  ('Kia', 'Tasman'),
  ('Kia', 'Optima'),
  ('Kia', 'Rondo'),
  ('Kia', 'Pregio'),
  ('LDV', 'T60'),
  ('LDV', 'T60 Max'),
  ('LDV', 'D90'),
  ('LDV', 'Deliver 9 Bus'),
  ('LDV', 'G10 Wagon'),
  ('LDV', 'MIFA 9'),
  ('LDV', 'eT60'),
  ('LDV', 'eDeliver 9 Bus'),
  ('Lamborghini', 'Aventador'),
  ('Lamborghini', 'Huracan'),
  ('Lamborghini', 'Urus'),
  ('Lamborghini', 'Revuelto'),
  ('Lamborghini', 'Gallardo'),
  ('Land Rover', 'Defender'),
  ('Land Rover', 'Discovery'),
  ('Land Rover', 'Discovery Sport'),
  ('Land Rover', 'Range Rover'),
  ('Land Rover', 'Range Rover Evoque'),
  ('Land Rover', 'Range Rover Sport'),
  ('Land Rover', 'Range Rover Velar'),
  ('Land Rover', 'Freelander'),
  ('Lexus', 'CT'),
  ('Lexus', 'ES'),
  ('Lexus', 'GS'),
  ('Lexus', 'GX'),
  ('Lexus', 'IS'),
  ('Lexus', 'LC'),
  ('Lexus', 'LS'),
  ('Lexus', 'LX'),
  ('Lexus', 'NX'),
  ('Lexus', 'RC'),
  ('Lexus', 'RX'),
  ('Lexus', 'RZ'),
  ('Lexus', 'UX'),
  ('Lexus', 'LBX'),
  ('Lexus', 'LM'),
  ('Lexus', 'TX'),
  ('Lotus', 'Elise'),
  ('Lotus', 'Emira'),
  ('Lotus', 'Evora'),
  ('Lotus', 'Exige'),
  ('Lotus', 'Eletre'),
  ('MG', 'MG3'),
  ('MG', 'MG4'),
  ('MG', 'MG5'),
  ('MG', 'ZS'),
  ('MG', 'ZS EV'),
  ('MG', 'HS'),
  ('MG', 'Cyberster'),
  ('MG', 'U9'),
  ('Maserati', 'Ghibli'),
  ('Maserati', 'Grecale'),
  ('Maserati', 'GranTurismo'),
  ('Maserati', 'Levante'),
  ('Maserati', 'MC20'),
  ('Maserati', 'Quattroporte'),
  ('Mazda', '2'),
  ('Mazda', '3'),
  ('Mazda', '6'),
  ('Mazda', 'BT-50'),
  ('Mazda', 'CX-3'),
  ('Mazda', 'CX-30'),
  ('Mazda', 'CX-5'),
  ('Mazda', 'CX-60'),
  ('Mazda', 'CX-70'),
  ('Mazda', 'CX-8'),
  ('Mazda', 'CX-9'),
  ('Mazda', 'CX-90'),
  ('Mazda', 'MX-5'),
  ('Mazda', 'MX-30'),
  ('Mazda', 'RX-8'),
  ('Mazda', 'Tribute'),
  ('McLaren', '570S'),
  ('McLaren', '600LT'),
  ('McLaren', '720S'),
  ('McLaren', '750S'),
  ('McLaren', 'Artura'),
  ('McLaren', 'GT'),
  ('Mercedes-Benz', 'A-Class'),
  ('Mercedes-Benz', 'B-Class'),
  ('Mercedes-Benz', 'C-Class'),
  ('Mercedes-Benz', 'CLA'),
  ('Mercedes-Benz', 'CLS'),
  ('Mercedes-Benz', 'E-Class'),
  ('Mercedes-Benz', 'G-Class'),
  ('Mercedes-Benz', 'GLA'),
  ('Mercedes-Benz', 'GLB'),
  ('Mercedes-Benz', 'GLC'),
  ('Mercedes-Benz', 'GLE'),
  ('Mercedes-Benz', 'GLS'),
  ('Mercedes-Benz', 'S-Class'),
  ('Mercedes-Benz', 'SL'),
  ('Mercedes-Benz', 'EQA'),
  ('Mercedes-Benz', 'EQB'),
  ('Mercedes-Benz', 'EQC'),
  ('Mercedes-Benz', 'EQE'),
  ('Mercedes-Benz', 'EQS'),
  ('Mercedes-Benz', 'V-Class'),
  ('Mercedes-Benz', 'X-Class'),
  ('Mercedes-Benz', 'AMG GT'),
  ('Mercedes-Benz', 'Valente'),
  ('Mini', 'Cooper'),
  ('Mini', 'Countryman'),
  ('Mini', 'Clubman'),
  ('Mini', 'Convertible'),
  ('Mini', 'Paceman'),
  ('Mini', 'Aceman'),
  ('Mitsubishi', 'ASX'),
  ('Mitsubishi', 'Eclipse Cross'),
  ('Mitsubishi', 'Lancer'),
  ('Mitsubishi', 'Mirage'),
  ('Mitsubishi', 'Outlander'),
  ('Mitsubishi', 'Pajero'),
  ('Mitsubishi', 'Pajero Sport'),
  ('Mitsubishi', 'Triton'),
  ('Mitsubishi', 'Express Wagon'),
  ('Mitsubishi', 'Challenger'),
  ('Mitsubishi', 'i-MiEV'),
  ('Mitsubishi', 'Magna'),
  ('Mitsubishi', '380'),
  ('Nissan', 'Ariya'),
  ('Nissan', 'Juke'),
  ('Nissan', 'Leaf'),
  ('Nissan', 'Micra'),
  ('Nissan', 'Murano'),
  ('Nissan', 'Navara'),
  ('Nissan', 'Pathfinder'),
  ('Nissan', 'Patrol'),
  ('Nissan', 'Pulsar'),
  ('Nissan', 'Qashqai'),
  ('Nissan', 'X-Trail'),
  ('Nissan', 'Z'),
  ('Nissan', 'GT-R'),
  ('Nissan', 'Dualis'),
  ('Nissan', 'Tiida'),
  ('Nissan', 'Skyline'),
  ('Nissan', 'Elgrand'),
  ('Peugeot', '208'),
  ('Peugeot', '308'),
  ('Peugeot', '408'),
  ('Peugeot', '508'),
  ('Peugeot', '2008'),
  ('Peugeot', '3008'),
  ('Peugeot', '5008'),
  ('Peugeot', 'Landtrek'),
  ('Peugeot', 'Rifter'),
  ('Polestar', '2'),
  ('Polestar', '3'),
  ('Polestar', '4'),
  ('Porsche', '911'),
  ('Porsche', '718 Boxster'),
  ('Porsche', '718 Cayman'),
  ('Porsche', 'Cayenne'),
  ('Porsche', 'Macan'),
  ('Porsche', 'Panamera'),
  ('Porsche', 'Taycan'),
  ('Ram', '1500'),
  ('Ram', '2500'),
  ('Ram', '3500'),
  ('Renault', 'Arkana'),
  ('Renault', 'Captur'),
  ('Renault', 'Clio'),
  ('Renault', 'Koleos'),
  ('Renault', 'Megane'),
  ('Renault', 'Megane E-Tech'),
  ('Renault', 'Kangoo Maxi Crew'),
  ('Renault', 'Trafic Crew Cab'),
  ('Renault', 'Fluence'),
  ('Renault', 'Scenic'),
  ('Rolls-Royce', 'Cullinan'),
  ('Rolls-Royce', 'Ghost'),
  ('Rolls-Royce', 'Phantom'),
  ('Rolls-Royce', 'Spectre'),
  ('Rolls-Royce', 'Wraith'),
  ('Rolls-Royce', 'Dawn'),
  ('Skoda', 'Fabia'),
  ('Skoda', 'Kamiq'),
  ('Skoda', 'Karoq'),
  ('Skoda', 'Kodiaq'),
  ('Skoda', 'Octavia'),
  ('Skoda', 'Scala'),
  ('Skoda', 'Superb'),
  ('Skoda', 'Enyaq'),
  ('Skoda', 'Roomster'),
  ('Skoda', 'Yeti'),
  ('Smart', '#1'),
  ('Smart', '#3'),
  ('Smart', 'ForTwo'),
  ('SsangYong', 'Korando'),
  ('SsangYong', 'Musso'),
  ('SsangYong', 'Rexton'),
  ('SsangYong', 'Tivoli'),
  ('SsangYong', 'Torres'),
  ('SsangYong', 'Actyon'),
  ('SsangYong', 'Stavic'),
  ('Subaru', 'BRZ'),
  ('Subaru', 'Crosstrek'),
  ('Subaru', 'Forester'),
  ('Subaru', 'Impreza'),
  ('Subaru', 'Liberty'),
  ('Subaru', 'Outback'),
  ('Subaru', 'Solterra'),
  ('Subaru', 'WRX'),
  ('Subaru', 'XV'),
  ('Subaru', 'Levorg'),
  ('Subaru', 'Tribeca'),
  ('Suzuki', 'Baleno'),
  ('Suzuki', 'Fronx'),
  ('Suzuki', 'Ignis'),
  ('Suzuki', 'Jimny'),
  ('Suzuki', 'S-Cross'),
  ('Suzuki', 'Swift'),
  ('Suzuki', 'Vitara'),
  ('Suzuki', 'Grand Vitara'),
  ('Suzuki', 'Alto'),
  ('Suzuki', 'Kizashi'),
  ('Suzuki', 'APV'),
  ('Tesla', 'Model 3'),
  ('Tesla', 'Model S'),
  ('Tesla', 'Model X'),
  ('Tesla', 'Model Y'),
  ('Tesla', 'Cybertruck'),
  ('Toyota', '86'),
  ('Toyota', 'GR86'),
  ('Toyota', 'bZ4X'),
  ('Toyota', 'C-HR'),
  ('Toyota', 'Camry'),
  ('Toyota', 'Corolla'),
  ('Toyota', 'Corolla Cross'),
  ('Toyota', 'FJ Cruiser'),
  ('Toyota', 'Fortuner'),
  ('Toyota', 'GR Corolla'),
  ('Toyota', 'GR Supra'),
  ('Toyota', 'GR Yaris'),
  ('Toyota', 'HiAce Commuter'),
  ('Toyota', 'HiLux'),
  ('Toyota', 'Kluger'),
  ('Toyota', 'LandCruiser'),
  ('Toyota', 'LandCruiser 70'),
  ('Toyota', 'LandCruiser Prado'),
  ('Toyota', 'Mirai'),
  ('Toyota', 'Prius'),
  ('Toyota', 'RAV4'),
  ('Toyota', 'Tarago'),
  ('Toyota', 'Yaris'),
  ('Toyota', 'Yaris Cross'),
  ('Toyota', 'Aurion'),
  ('Toyota', 'Avalon'),
  ('Toyota', 'Echo'),
  ('Toyota', 'Granvia'),
  ('Volkswagen', 'Amarok'),
  ('Volkswagen', 'Arteon'),
  ('Volkswagen', 'Caddy'),
  ('Volkswagen', 'California'),
  ('Volkswagen', 'Golf'),
  ('Volkswagen', 'Golf GTI'),
  ('Volkswagen', 'Golf R'),
  ('Volkswagen', 'ID.4'),
  ('Volkswagen', 'ID.5'),
  ('Volkswagen', 'ID. Buzz'),
  ('Volkswagen', 'Jetta'),
  ('Volkswagen', 'Multivan'),
  ('Volkswagen', 'Passat'),
  ('Volkswagen', 'Polo'),
  ('Volkswagen', 'T-Cross'),
  ('Volkswagen', 'T-Roc'),
  ('Volkswagen', 'Tiguan'),
  ('Volkswagen', 'Touareg'),
  ('Volkswagen', 'Beetle'),
  ('Volkswagen', 'Scirocco'),
  ('Volvo', 'C40'),
  ('Volvo', 'EX30'),
  ('Volvo', 'EX40'),
  ('Volvo', 'EX90'),
  ('Volvo', 'S60'),
  ('Volvo', 'S90'),
  ('Volvo', 'V40'),
  ('Volvo', 'V60'),
  ('Volvo', 'V90'),
  ('Volvo', 'XC40'),
  ('Volvo', 'XC60'),
  ('Volvo', 'XC90'),
  ('Zeekr', '001'),
  ('Zeekr', '7X'),
  ('Zeekr', 'X')
) as v(make, model)
join public.vehicle_makes mk on mk.name = v.make
on conflict (make_id, name) do nothing;
